// Server configuration properties
handshakePort=7000

keystoreFile=server_keystore.p12
keystorePassword=PASSWORD
keyAlias=streamserver
keyPassword=PASSWORD

// Client configuration properties
cipher=CHACHA20_POLY1305
serverHost=127.0.0.1
serverCertificateFile=server_cert.pem
handshakePort=7000

remote=127.0.0.1:5000
localdelivery=127.0.0.1:6000
